### ISSUE TITLE
Publish release information to GitHub

### ISSUE THREAD

**Issue by winstonpuckett** [winstonpuckett/lucifer#1]
As someone evaluating CLI testing options, I'd like to know all of the versions which have been published in recent history.

As a developer on the lucifer project, I'd like release management to be automated and centralized between tools.

As someone promoting lucifer, I'd like to fill out the splash page when someone lands on the lucifer project on GitHub.

To this end,
- Given a trigger for a new release, when the version is published, then a release on the lucifer project page should be automatically created with the correct version number, release notes, and the places you can install the project.

**Comment by ivy-puckett** [comment]
It looks like publishing to cargo didn't update the version number. It's currently 0.0.0.

**Comment by ivy-puckett** [comment]
Current build system now triggers successfully with tagging: 
git commit -am"any message"
git push
git tag 0.1.XX
git push origin --tags
