### ISSUE TITLE
Output all test info to results.json

### ISSUE THREAD

**Issue by winstonpuckett** [winstonpuckett/lucifer#5]
Currently we're only outputing performance and failures. We need to include all the information we can so that downstream systems can make reasonable decisions.

**Comment by ivy-puckett** [comment]
Now that I'm addressing this, I wish I would have notated what "all information" means 😆

**Comment by ivy-puckett** [comment]
I just included every piece of information I could find. Features are noted per test, which may increase the file size significantly if there are a lot of tests. If this becomes a problem for users, we'll have to change that.
